### ISSUE TITLE
When any image loads, it throws 'System.ArgumentException'

### ISSUE THREAD

**Issue by luandersonn** [HHChaos/ImageCropper#3]
"Value does not fall within the expected range."

![image](https://user-images.githubusercontent.com/30560453/51806085-37c89400-2254-11e9-9b38-3065bee66a49.png)
![image](https://user-images.githubusercontent.com/30560453/51806280-f4235980-2256-11e9-8e94-c8a1cf9bbcdd.png)

XAML:
`
<StackPane>
<Button Content="Open" Click="Button_Click"/>
<hhchaos:ImageCropper x:Name="cropper">
</StackPanel>`

StackTrace:
`at Windows.UI.Xaml.Media.CompositeTransform.put_ScaleY(Double value)
at ImageCropper.UWP.ImageCropper.UpdateImageLayoutWithViewport(Rect viewport, Rect viewportImageRect, Boolean animate)
at ImageCropper.UWP.ImageCropper.UpdateImageLayout(Boolean animate)
at ImageCropper.UWP.ImageCropper.InitImageLayout(Boolean animate)
at ImageCropper.UWP.ImageCropper.OnSourceImageChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
at Windows.UI.Xaml.DependencyObject.SetValue(DependencyProperty dp, Object value)
at ImageCropper.UWP.ImageCropper.LoadImageFromFile(StorageFile imageFile)
at Aluno_UFC.Pages.NavigationPages.PageHome.Button_Click(Object sender, RoutedEventArgs e)`

**Comment by HHChaos** [comment]
@luandersonn Thanks for your feedback!
When you put ImageCropper in the `StackPanel`, its `_imageCanvas.ActualHeight` is 0, so you need to give it a valid height.
I'll try to solve the problem.

**Comment by HHChaos** [comment]
@luandersonn I pushed a new nuget package to fix the bug.
https://www.nuget.org/packages/ImageCropper.UWP/1.2.1

**Comment by luandersonn** [comment]
> 
> 
> @luandersonn I pushed a new nuget package to fix the bug.
> https://www.nuget.org/packages/ImageCropper.UWP/1.2.1

Thanks!
